// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::ClientDisconnect message and its fields.

#pragma once

#include "mqtt5/field/ClientDisconnectPropertyListCommon.h"
#include "mqtt5/field/DisconnectReasonCodeCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of
///     @ref mqtt5::message::ClientDisconnect message.
/// @see mqtt5::message::ClientDisconnectFields
struct ClientDisconnectFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ClientDisconnectFields::ReasonCode field.
    using ReasonCodeCommon = mqtt5::field::DisconnectReasonCodeCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ClientDisconnectFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::ClientDisconnectPropertyListMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ClientDisconnectFields::Properties field.
    using PropertiesCommon = mqtt5::field::ClientDisconnectPropertyListCommon;

};

/// @brief Common types and functions of
///     @ref mqtt5::message::ClientDisconnect message.
struct ClientDisconnectCommon
{
    /// @brief Name of the @ref mqtt5::message::ClientDisconnect message.
    static const char* name()
    {
        return "DISCONNECT";
    }

};

} // namespace message

} // namespace mqtt5



