// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Connect message and its fields.

#pragma once

#include "mqtt5/field/ClientIdCommon.h"
#include "mqtt5/field/ConnectFlagsCommon.h"
#include "mqtt5/field/ConnectPropertiesCommon.h"
#include "mqtt5/field/KeepAliveCommon.h"
#include "mqtt5/field/OptionalPasswordCommon.h"
#include "mqtt5/field/OptionalUserNameCommon.h"
#include "mqtt5/field/OptionalWillPayloadCommon.h"
#include "mqtt5/field/OptionalWillPropertiesCommon.h"
#include "mqtt5/field/OptionalWillTopicCommon.h"
#include "mqtt5/field/ProtocolNameCommon.h"
#include "mqtt5/field/ProtocolVersionCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of
///     @ref mqtt5::message::Connect message.
/// @see mqtt5::message::ConnectFields
struct ConnectFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::ProtocolName field.
    using ProtocolNameCommon = mqtt5::field::ProtocolNameCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::ProtocolVersion field.
    using ProtocolVersionCommon = mqtt5::field::ProtocolVersionCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::Flags field.
    using FlagsMembersCommon = mqtt5::field::ConnectFlagsMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::Flags field.
    using FlagsCommon = mqtt5::field::ConnectFlagsCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::KeepAlive field.
    using KeepAliveCommon = mqtt5::field::KeepAliveCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::ConnectPropertiesMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::Properties field.
    using PropertiesCommon = mqtt5::field::ConnectPropertiesCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::ClientId field.
    using ClientIdCommon = mqtt5::field::ClientIdCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::WillProperties field.
    using WillPropertiesMembersCommon = mqtt5::field::OptionalWillPropertiesMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::WillProperties field.
    using WillPropertiesCommon = mqtt5::field::OptionalWillPropertiesCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::WillTopic field.
    using WillTopicMembersCommon = mqtt5::field::OptionalWillTopicMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::WillTopic field.
    using WillTopicCommon = mqtt5::field::OptionalWillTopicCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::WillPayload field.
    using WillPayloadMembersCommon = mqtt5::field::OptionalWillPayloadMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::WillPayload field.
    using WillPayloadCommon = mqtt5::field::OptionalWillPayloadCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::UserName field.
    using UserNameMembersCommon = mqtt5::field::OptionalUserNameMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::UserName field.
    using UserNameCommon = mqtt5::field::OptionalUserNameCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::ConnectFields::Password field.
    using PasswordMembersCommon = mqtt5::field::OptionalPasswordMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::ConnectFields::Password field.
    struct PasswordCommon : public mqtt5::field::OptionalPasswordCommon
    {
        /// @brief Name of the @ref mqtt5::message::ConnectFields::Password field.
        static const char* name()
        {
            return "Password";
        }

    };

};

/// @brief Common types and functions of
///     @ref mqtt5::message::Connect message.
struct ConnectCommon
{
    /// @brief Name of the @ref mqtt5::message::Connect message.
    static const char* name()
    {
        return "CONNECT";
    }

};

} // namespace message

} // namespace mqtt5



