// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Disconnect message and its fields.

#pragma once

#include "mqtt5/field/DisconnectPropertyListCommon.h"
#include "mqtt5/field/DisconnectReasonCodeCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of 
///     @ref mqtt5::message::Disconnect message.
/// @see mqtt5::message::DisconnectFields
struct DisconnectFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::DisconnectFields::ReasonCode field.
    using ReasonCodeCommon = mqtt5::field::DisconnectReasonCodeCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::DisconnectFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::DisconnectPropertyListMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::DisconnectFields::Properties field.
    using PropertiesCommon = mqtt5::field::DisconnectPropertyListCommon;
    
};

/// @brief Common types and functions of 
///     @ref mqtt5::message::Disconnect message.
struct DisconnectCommon
{
    /// @brief Name of the @ref mqtt5::message::Disconnect message.
    static const char* name()
    {
        return "DISCONNECT";
    }
    
};

} // namespace message

} // namespace mqtt5



