// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Publish message and its fields.

#pragma once

#include "mqtt5/field/OptionalPacketIdentifierCommon.h"
#include "mqtt5/field/PublishPropertiesCommon.h"
#include "mqtt5/field/TopicNameCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of
///     @ref mqtt5::message::Publish message.
/// @see mqtt5::message::PublishFields
struct PublishFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PublishFields::TopicName field.
    using TopicNameCommon = mqtt5::field::TopicNameCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::PublishFields::PacketId field.
    using PacketIdMembersCommon = mqtt5::field::OptionalPacketIdentifierMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PublishFields::PacketId field.
    using PacketIdCommon = mqtt5::field::OptionalPacketIdentifierCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::PublishFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::PublishPropertiesMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PublishFields::Properties field.
    using PropertiesCommon = mqtt5::field::PublishPropertiesCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PublishFields::Payload field.
    struct PayloadCommon
    {
        /// @brief Name of the @ref mqtt5::message::PublishFields::Payload field.
        static const char* name()
        {
            return "Payload";
        }

    };

};

/// @brief Common types and functions of
///     @ref mqtt5::message::Publish message.
struct PublishCommon
{
    /// @brief Name of the @ref mqtt5::message::Publish message.
    static const char* name()
    {
        return "PUBLISH";
    }

};

} // namespace message

} // namespace mqtt5



