// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Pubrec message and its fields.

#pragma once

#include "mqtt5/field/PacketIdentifierCommon.h"
#include "mqtt5/field/PubrecPropertiesCommon.h"
#include "mqtt5/field/PubrecReasonCodeCommon.h"

namespace mqtt5
{

namespace message
{

/// @brief Common types and functions for fields of
///     @ref mqtt5::message::Pubrec message.
/// @see mqtt5::message::PubrecFields
struct PubrecFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PubrecFields::PacketId field.
    struct PacketIdCommon : public mqtt5::field::PacketIdentifierCommon
    {
        /// @brief Name of the @ref mqtt5::message::PubrecFields::PacketId field.
        static const char* name()
        {
            return "Packet ID";
        }
    };

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PubrecFields::ReasonCode field.
    using ReasonCodeCommon = mqtt5::field::PubrecReasonCodeCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::PubrecFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::PubrecPropertiesMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PubrecFields::Properties field.
    using PropertiesCommon = mqtt5::field::PubrecPropertiesCommon;
};

/// @brief Common types and functions of
///     @ref mqtt5::message::Pubrec message.
struct PubrecCommon
{
    /// @brief Name of the @ref mqtt5::message::Pubrec message.
    static const char* name()
    {
        return "PUBREC";
    }
};

} // namespace message

} // namespace mqtt5
