// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Pubrel message and its fields.

#pragma once

#include "mqtt5/field/PacketIdCommon.h"
#include "mqtt5/field/PubackPropertyListCommon.h"
#include "mqtt5/field/PubackReasonCodeCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of 
///     @ref mqtt5::message::Pubrel message.
/// @see mqtt5::message::PubrelFields
struct PubrelFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PubrelFields::PacketId field.
    using PacketIdCommon = mqtt5::field::PacketIdCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PubrelFields::ReasonCode field.
    using ReasonCodeCommon = mqtt5::field::PubackReasonCodeCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::PubrelFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::PubackPropertyListMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::PubrelFields::Properties field.
    using PropertiesCommon = mqtt5::field::PubackPropertyListCommon;
    
};

/// @brief Common types and functions of 
///     @ref mqtt5::message::Pubrel message.
struct PubrelCommon
{
    /// @brief Name of the @ref mqtt5::message::Pubrel message.
    static const char* name()
    {
        return "PUBREL";
    }
    
};

} // namespace message

} // namespace mqtt5



