// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Suback message and its fields.

#pragma once

#include "mqtt5/field/PacketIdCommon.h"
#include "mqtt5/field/SubackPropertyListCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of 
///     @ref mqtt5::message::Suback message.
/// @see mqtt5::message::SubackFields
struct SubackFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::SubackFields::PacketId field.
    using PacketIdCommon = mqtt5::field::PacketIdCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::SubackFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::SubackPropertyListMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::SubackFields::Properties field.
    using PropertiesCommon = mqtt5::field::SubackPropertyListCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::SubackFields::List field.
    struct ListCommon
    {
        /// @brief Name of the @ref mqtt5::message::SubackFields::List field.
        static const char* name()
        {
            return "List";
        }
        
    };
    
};

/// @brief Common types and functions of 
///     @ref mqtt5::message::Suback message.
struct SubackCommon
{
    /// @brief Name of the @ref mqtt5::message::Suback message.
    static const char* name()
    {
        return "SUBACK";
    }
    
};

} // namespace message

} // namespace mqtt5



