// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Unsubscribe message and its fields.

#pragma once

#include "mqtt5/field/PacketIdCommon.h"
#include "mqtt5/field/UnsubscribePropertyListCommon.h"

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions for fields of 
///     @ref mqtt5::message::Unsubscribe message.
/// @see mqtt5::message::UnsubscribeFields
struct UnsubscribeFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::UnsubscribeFields::PacketId field.
    using PacketIdCommon = mqtt5::field::PacketIdCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::message::UnsubscribeFields::Properties field.
    using PropertiesMembersCommon = mqtt5::field::UnsubscribePropertyListMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::UnsubscribeFields::Properties field.
    using PropertiesCommon = mqtt5::field::UnsubscribePropertyListCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::message::UnsubscribeFields::List field.
    struct ListCommon
    {
        /// @brief Name of the @ref mqtt5::message::UnsubscribeFields::List field.
        static const char* name()
        {
            return "List";
        }
        
    };
    
};

/// @brief Common types and functions of 
///     @ref mqtt5::message::Unsubscribe message.
struct UnsubscribeCommon
{
    /// @brief Name of the @ref mqtt5::message::Unsubscribe message.
    static const char* name()
    {
        return "UNSUBSCRIBE";
    }
    
};

} // namespace message

} // namespace mqtt5



