// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"Client ID"</b> field.

#pragma once

#include "comms/options.h"
#include "mqtt5/field/ClientIdCommon.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/Utf8String.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{

/// @brief Definition of <b>"Client ID"</b> field.
/// @details
///     Defined in section 3.1.3.1.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class ClientId : public
    mqtt5::field::Utf8String<
        TOpt,
        TExtraOpts...
    >
{
    using Base =
        mqtt5::field::Utf8String<
            TOpt,
            TExtraOpts...
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::ClientIdCommon::name();
    }
};

} // namespace field

} // namespace mqtt5
