// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"Client Reason Code"</b> field.

#pragma once

#include "comms/field/EnumValue.h"
#include "comms/options.h"
#include "mqtt5/field/ClientAuthReasonCodeCommon.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Definition of <b>"Client Reason Code"</b> field.
/// @details
///     Defined in section 3.15.2.1.
/// @see @ref mqtt5::field::ClientAuthReasonCodeCommon::ValueType
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class ClientAuthReasonCode : public
    comms::field::EnumValue<
        mqtt5::field::FieldBase<>,
        mqtt5::field::ClientAuthReasonCodeCommon::ValueType,
        TExtraOpts...,
        comms::option::def::ValidNumValueRange<24, 25>
    >
{
    using Base =
        comms::field::EnumValue<
            mqtt5::field::FieldBase<>,
            mqtt5::field::ClientAuthReasonCodeCommon::ValueType,
            TExtraOpts...,
            comms::option::def::ValidNumValueRange<24, 25>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;

    /// @brief Single value name info entry.
    using ValueNameInfo = mqtt5::field::ClientAuthReasonCodeCommon::ValueNameInfo;

    /// @brief Type returned from @ref valueNamesMap() member function.
    /// @see @ref mqtt5::field::ClientAuthReasonCodeCommon::ValueNamesMapInfo.
    using ValueNamesMapInfo = mqtt5::field::ClientAuthReasonCodeCommon::ValueNamesMapInfo;

    /// @brief Retrieve name of the enum value.
    /// @see @ref mqtt5::field::ClientAuthReasonCodeCommon::valueName().
    static const char* valueName(ValueType val)
    {
        return mqtt5::field::ClientAuthReasonCodeCommon::valueName(val);
    }

    /// @brief Retrieve name of the @b current value
    const char* valueName() const
    {
        return valueName(Base::value());
    }

    /// @brief Retrieve map of enum value names.
    /// @see @ref mqtt5::field::ClientAuthReasonCodeCommon::valueNamesMap().
    static ValueNamesMapInfo valueNamesMap()
    {
        return mqtt5::field::ClientAuthReasonCodeCommon::valueNamesMap();
    }


    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::ClientAuthReasonCodeCommon::name();
    }


};


} // namespace field

} // namespace mqtt5

