// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::ConnackProperty field.

#pragma once

#include "mqtt5/field/AssignedClientIdCommon.h"
#include "mqtt5/field/AuthDataCommon.h"
#include "mqtt5/field/AuthMethodCommon.h"
#include "mqtt5/field/MaxPacketSizeCommon.h"
#include "mqtt5/field/MaxQosCommon.h"
#include "mqtt5/field/ReasonStrCommon.h"
#include "mqtt5/field/ReceiveMaxCommon.h"
#include "mqtt5/field/ResponseInfoCommon.h"
#include "mqtt5/field/RetainAvailableCommon.h"
#include "mqtt5/field/ServerKeepAliveCommon.h"
#include "mqtt5/field/ServerRefCommon.h"
#include "mqtt5/field/SessionExpiryIntervalCommon.h"
#include "mqtt5/field/SharedSubAvailCommon.h"
#include "mqtt5/field/SubIdAvailCommon.h"
#include "mqtt5/field/TopicAliasMaxCommon.h"
#include "mqtt5/field/UserPropertyCommon.h"
#include "mqtt5/field/WildcardSubAvailCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::ConnackProperty field.
struct ConnackPropertyMembersCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::SessionExpiryInterval field.
    using SessionExpiryIntervalMembersCommon = mqtt5::field::SessionExpiryIntervalMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::SessionExpiryInterval field.
    using SessionExpiryIntervalCommon = mqtt5::field::SessionExpiryIntervalCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::ReceiveMax field.
    using ReceiveMaxMembersCommon = mqtt5::field::ReceiveMaxMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::ReceiveMax field.
    using ReceiveMaxCommon = mqtt5::field::ReceiveMaxCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::MaxQos field.
    using MaxQosMembersCommon = mqtt5::field::MaxQosMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::MaxQos field.
    using MaxQosCommon = mqtt5::field::MaxQosCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::RetainAvailable field.
    using RetainAvailableMembersCommon = mqtt5::field::RetainAvailableMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::RetainAvailable field.
    using RetainAvailableCommon = mqtt5::field::RetainAvailableCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::MaxPacketSize field.
    using MaxPacketSizeMembersCommon = mqtt5::field::MaxPacketSizeMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::MaxPacketSize field.
    using MaxPacketSizeCommon = mqtt5::field::MaxPacketSizeCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::AssignedClientId field.
    using AssignedClientIdMembersCommon = mqtt5::field::AssignedClientIdMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::AssignedClientId field.
    using AssignedClientIdCommon = mqtt5::field::AssignedClientIdCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::TopicAliasMax field.
    using TopicAliasMaxMembersCommon = mqtt5::field::TopicAliasMaxMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::TopicAliasMax field.
    using TopicAliasMaxCommon = mqtt5::field::TopicAliasMaxCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::ReasonStr field.
    using ReasonStrMembersCommon = mqtt5::field::ReasonStrMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::ReasonStr field.
    using ReasonStrCommon = mqtt5::field::ReasonStrCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::UserProperty field.
    using UserPropertyMembersCommon = mqtt5::field::UserPropertyMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::UserProperty field.
    using UserPropertyCommon = mqtt5::field::UserPropertyCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::WildcardSubAvail field.
    using WildcardSubAvailMembersCommon = mqtt5::field::WildcardSubAvailMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::WildcardSubAvail field.
    using WildcardSubAvailCommon = mqtt5::field::WildcardSubAvailCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::SubIdAvail field.
    using SubIdAvailMembersCommon = mqtt5::field::SubIdAvailMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::SubIdAvail field.
    using SubIdAvailCommon = mqtt5::field::SubIdAvailCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::SharedSubAvail field.
    using SharedSubAvailMembersCommon = mqtt5::field::SharedSubAvailMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::SharedSubAvail field.
    using SharedSubAvailCommon = mqtt5::field::SharedSubAvailCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::ServerKeepAlive field.
    using ServerKeepAliveMembersCommon = mqtt5::field::ServerKeepAliveMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::ServerKeepAlive field.
    using ServerKeepAliveCommon = mqtt5::field::ServerKeepAliveCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::ResponseInfo field.
    using ResponseInfoMembersCommon = mqtt5::field::ResponseInfoMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::ResponseInfo field.
    using ResponseInfoCommon = mqtt5::field::ResponseInfoCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::ServerRef field.
    using ServerRefMembersCommon = mqtt5::field::ServerRefMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::ServerRef field.
    using ServerRefCommon = mqtt5::field::ServerRefCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::AuthMethod field.
    using AuthMethodMembersCommon = mqtt5::field::AuthMethodMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::AuthMethod field.
    using AuthMethodCommon = mqtt5::field::AuthMethodCommon;
    
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::ConnackPropertyMembers::AuthData field.
    using AuthDataMembersCommon = mqtt5::field::AuthDataMembersCommon;
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ConnackPropertyMembers::AuthData field.
    using AuthDataCommon = mqtt5::field::AuthDataCommon;
    
};

/// @brief Common types and functions for
///     @ref mqtt5::field::ConnackProperty field.
struct ConnackPropertyCommon
{
    /// @brief Name of the @ref mqtt5::field::ConnackProperty field.
    static const char* name()
    {
        return "";
    }
    
};

} // namespace field

} // namespace mqtt5

