// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>""</b> field.

#pragma once

#include <tuple>
#include "comms/CompileControl.h"
#include "comms/field/Variant.h"
#include "comms/options.h"
#include "mqtt5/field/ConnackPropertyCommon.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/PropertyAssignedClientId.h"
#include "mqtt5/field/PropertyAuthData.h"
#include "mqtt5/field/PropertyAuthMethod.h"
#include "mqtt5/field/PropertyMaxPacketSize.h"
#include "mqtt5/field/PropertyMaxQos.h"
#include "mqtt5/field/PropertyReasonString.h"
#include "mqtt5/field/PropertyReceiveMax.h"
#include "mqtt5/field/PropertyResponseInfo.h"
#include "mqtt5/field/PropertyRetainAvailable.h"
#include "mqtt5/field/PropertyServerKeepAlive.h"
#include "mqtt5/field/PropertyServerReference.h"
#include "mqtt5/field/PropertySessionExpiryInterval.h"
#include "mqtt5/field/PropertySharedSubAvail.h"
#include "mqtt5/field/PropertySubIdAvail.h"
#include "mqtt5/field/PropertyTopicAliasMax.h"
#include "mqtt5/field/PropertyUserProperty.h"
#include "mqtt5/field/PropertyWildcardSubAvail.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the member fields of
///     @ref ConnackProperty field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct ConnackPropertyMembers
{
    /// @brief Definition of <b>"Session Expiry Interval"</b> field.
    using SessionExpiryInterval =
        mqtt5::field::PropertySessionExpiryInterval<
            TOpt
        >;


    /// @brief Definition of <b>"Receive Maximum"</b> field.
    using ReceiveMax =
        mqtt5::field::PropertyReceiveMax<
            TOpt
        >;


    /// @brief Definition of <b>"Maximum QoS"</b> field.
    using MaxQos =
        mqtt5::field::PropertyMaxQos<
            TOpt
        >;


    /// @brief Definition of <b>"Retain Available"</b> field.
    using RetainAvailable =
        mqtt5::field::PropertyRetainAvailable<
            TOpt
        >;


    /// @brief Definition of <b>"Maximum Packet Size"</b> field.
    using MaxPacketSize =
        mqtt5::field::PropertyMaxPacketSize<
            TOpt
        >;


    /// @brief Definition of <b>"Assigned Client ID"</b> field.
    using AssignedClientId =
        mqtt5::field::PropertyAssignedClientId<
            TOpt
        >;


    /// @brief Definition of <b>"Topic Alias Maximum"</b> field.
    using TopicAliasMax =
        mqtt5::field::PropertyTopicAliasMax<
            TOpt
        >;


    /// @brief Definition of <b>"Reason String"</b> field.
    using ReasonString =
        mqtt5::field::PropertyReasonString<
            TOpt
        >;


    /// @brief Definition of <b>"User Property"</b> field.
    using UserProperty =
        mqtt5::field::PropertyUserProperty<
            TOpt
        >;


    /// @brief Definition of <b>"Wildcard Subscription Available"</b> field.
    using WildcardSubAvail =
        mqtt5::field::PropertyWildcardSubAvail<
            TOpt
        >;


    /// @brief Definition of <b>"Subscription ID Available"</b> field.
    using SubIdAvail =
        mqtt5::field::PropertySubIdAvail<
            TOpt
        >;


    /// @brief Definition of <b>"Shared Subscription Available"</b> field.
    using SharedSubAvail =
        mqtt5::field::PropertySharedSubAvail<
            TOpt
        >;


    /// @brief Definition of <b>"Server Keep Alive"</b> field.
    using ServerKeepAlive =
        mqtt5::field::PropertyServerKeepAlive<
            TOpt
        >;


    /// @brief Definition of <b>"Response Information"</b> field.
    using ResponseInfo =
        mqtt5::field::PropertyResponseInfo<
            TOpt
        >;


    /// @brief Definition of <b>"Server Reference"</b> field.
    using ServerReference =
        mqtt5::field::PropertyServerReference<
            TOpt
        >;


    /// @brief Definition of <b>"Authentication Method"</b> field.
    using AuthMethod =
        mqtt5::field::PropertyAuthMethod<
            TOpt
        >;


    /// @brief Definition of <b>"Authentication Data"</b> field.
    using AuthData =
        mqtt5::field::PropertyAuthData<
            TOpt
        >;


    /// @brief All members bundled in @b std::tuple.
    using All =
        std::tuple<
           SessionExpiryInterval,
           ReceiveMax,
           MaxQos,
           RetainAvailable,
           MaxPacketSize,
           AssignedClientId,
           TopicAliasMax,
           ReasonString,
           UserProperty,
           WildcardSubAvail,
           SubIdAvail,
           SharedSubAvail,
           ServerKeepAlive,
           ResponseInfo,
           ServerReference,
           AuthMethod,
           AuthData
        >;
};

/// @brief Definition of <b>""</b> field.
/// @details
///     Defined in section 3.2.2.3.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class ConnackProperty : public
    comms::field::Variant<
        mqtt5::field::FieldBase<>,
        typename ConnackPropertyMembers<TOpt>::All,
        TExtraOpts...
    >
{
    using Base =
        comms::field::Variant<
            mqtt5::field::FieldBase<>,
            typename ConnackPropertyMembers<TOpt>::All,
            TExtraOpts...
        >;
public:
    /// @brief Allow access to internal fields.
    /// @details See definition of @b COMMS_VARIANT_MEMBERS_NAMES macro
    ///     related to @b comms::field::Variant class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and access functions are:
    ///     @li @b FieldIdx_sessionExpiryInterval index, @b Field_sessionExpiryInterval type,
    ///         @b initField_sessionExpiryInterval() and @b accessField_sessionExpiryInterval() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::SessionExpiryInterval member field.
    ///     @li @b FieldIdx_receiveMax index, @b Field_receiveMax type,
    ///         @b initField_receiveMax() and @b accessField_receiveMax() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::ReceiveMax member field.
    ///     @li @b FieldIdx_maxQos index, @b Field_maxQos type,
    ///         @b initField_maxQos() and @b accessField_maxQos() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::MaxQos member field.
    ///     @li @b FieldIdx_retainAvailable index, @b Field_retainAvailable type,
    ///         @b initField_retainAvailable() and @b accessField_retainAvailable() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::RetainAvailable member field.
    ///     @li @b FieldIdx_maxPacketSize index, @b Field_maxPacketSize type,
    ///         @b initField_maxPacketSize() and @b accessField_maxPacketSize() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::MaxPacketSize member field.
    ///     @li @b FieldIdx_assignedClientId index, @b Field_assignedClientId type,
    ///         @b initField_assignedClientId() and @b accessField_assignedClientId() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::AssignedClientId member field.
    ///     @li @b FieldIdx_topicAliasMax index, @b Field_topicAliasMax type,
    ///         @b initField_topicAliasMax() and @b accessField_topicAliasMax() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::TopicAliasMax member field.
    ///     @li @b FieldIdx_reasonString index, @b Field_reasonString type,
    ///         @b initField_reasonString() and @b accessField_reasonString() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::ReasonString member field.
    ///     @li @b FieldIdx_userProperty index, @b Field_userProperty type,
    ///         @b initField_userProperty() and @b accessField_userProperty() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::UserProperty member field.
    ///     @li @b FieldIdx_wildcardSubAvail index, @b Field_wildcardSubAvail type,
    ///         @b initField_wildcardSubAvail() and @b accessField_wildcardSubAvail() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::WildcardSubAvail member field.
    ///     @li @b FieldIdx_subIdAvail index, @b Field_subIdAvail type,
    ///         @b initField_subIdAvail() and @b accessField_subIdAvail() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::SubIdAvail member field.
    ///     @li @b FieldIdx_sharedSubAvail index, @b Field_sharedSubAvail type,
    ///         @b initField_sharedSubAvail() and @b accessField_sharedSubAvail() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::SharedSubAvail member field.
    ///     @li @b FieldIdx_serverKeepAlive index, @b Field_serverKeepAlive type,
    ///         @b initField_serverKeepAlive() and @b accessField_serverKeepAlive() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::ServerKeepAlive member field.
    ///     @li @b FieldIdx_responseInfo index, @b Field_responseInfo type,
    ///         @b initField_responseInfo() and @b accessField_responseInfo() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::ResponseInfo member field.
    ///     @li @b FieldIdx_serverReference index, @b Field_serverReference type,
    ///         @b initField_serverReference() and @b accessField_serverReference() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::ServerReference member field.
    ///     @li @b FieldIdx_authMethod index, @b Field_authMethod type,
    ///         @b initField_authMethod() and @b accessField_authMethod() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::AuthMethod member field.
    ///     @li @b FieldIdx_authData index, @b Field_authData type,
    ///         @b initField_authData() and @b accessField_authData() access functions -
    ///         for mqtt5::field::ConnackPropertyMembers::AuthData member field.
    COMMS_VARIANT_MEMBERS_NAMES(
        sessionExpiryInterval,
        receiveMax,
        maxQos,
        retainAvailable,
        maxPacketSize,
        assignedClientId,
        topicAliasMax,
        reasonString,
        userProperty,
        wildcardSubAvail,
        subIdAvail,
        sharedSubAvail,
        serverKeepAlive,
        responseInfo,
        serverReference,
        authMethod,
        authData
    );

    /// @brief Optimized currFieldExec functionality.
    /// @details Replaces the currFieldExec() member function defined
    ///    by @b comms::field::Variant.
    template <typename TFunc>
    void currFieldExec(TFunc&& func)
    {
        switch (Base::currentField()) {
        case FieldIdx_sessionExpiryInterval:
            memFieldDispatch<FieldIdx_sessionExpiryInterval>(accessField_sessionExpiryInterval(), std::forward<TFunc>(func));
            break;
        case FieldIdx_receiveMax:
            memFieldDispatch<FieldIdx_receiveMax>(accessField_receiveMax(), std::forward<TFunc>(func));
            break;
        case FieldIdx_maxQos:
            memFieldDispatch<FieldIdx_maxQos>(accessField_maxQos(), std::forward<TFunc>(func));
            break;
        case FieldIdx_retainAvailable:
            memFieldDispatch<FieldIdx_retainAvailable>(accessField_retainAvailable(), std::forward<TFunc>(func));
            break;
        case FieldIdx_maxPacketSize:
            memFieldDispatch<FieldIdx_maxPacketSize>(accessField_maxPacketSize(), std::forward<TFunc>(func));
            break;
        case FieldIdx_assignedClientId:
            memFieldDispatch<FieldIdx_assignedClientId>(accessField_assignedClientId(), std::forward<TFunc>(func));
            break;
        case FieldIdx_topicAliasMax:
            memFieldDispatch<FieldIdx_topicAliasMax>(accessField_topicAliasMax(), std::forward<TFunc>(func));
            break;
        case FieldIdx_reasonString:
            memFieldDispatch<FieldIdx_reasonString>(accessField_reasonString(), std::forward<TFunc>(func));
            break;
        case FieldIdx_userProperty:
            memFieldDispatch<FieldIdx_userProperty>(accessField_userProperty(), std::forward<TFunc>(func));
            break;
        case FieldIdx_wildcardSubAvail:
            memFieldDispatch<FieldIdx_wildcardSubAvail>(accessField_wildcardSubAvail(), std::forward<TFunc>(func));
            break;
        case FieldIdx_subIdAvail:
            memFieldDispatch<FieldIdx_subIdAvail>(accessField_subIdAvail(), std::forward<TFunc>(func));
            break;
        case FieldIdx_sharedSubAvail:
            memFieldDispatch<FieldIdx_sharedSubAvail>(accessField_sharedSubAvail(), std::forward<TFunc>(func));
            break;
        case FieldIdx_serverKeepAlive:
            memFieldDispatch<FieldIdx_serverKeepAlive>(accessField_serverKeepAlive(), std::forward<TFunc>(func));
            break;
        case FieldIdx_responseInfo:
            memFieldDispatch<FieldIdx_responseInfo>(accessField_responseInfo(), std::forward<TFunc>(func));
            break;
        case FieldIdx_serverReference:
            memFieldDispatch<FieldIdx_serverReference>(accessField_serverReference(), std::forward<TFunc>(func));
            break;
        case FieldIdx_authMethod:
            memFieldDispatch<FieldIdx_authMethod>(accessField_authMethod(), std::forward<TFunc>(func));
            break;
        case FieldIdx_authData:
            memFieldDispatch<FieldIdx_authData>(accessField_authData(), std::forward<TFunc>(func));
            break;
        default:
            static constexpr bool Invalid_field_execution = false;
            static_cast<void>(Invalid_field_execution);
            COMMS_ASSERT(Invalid_field_execution);
            break;
        }
    }

    /// @brief Optimized currFieldExec functionality (const variant).
    /// @details Replaces the currFieldExec() member function defined
    ///    by @b comms::field::Variant.
    template <typename TFunc>
    void currFieldExec(TFunc&& func) const
    {
        switch (Base::currentField()) {
        case FieldIdx_sessionExpiryInterval:
            memFieldDispatch<FieldIdx_sessionExpiryInterval>(accessField_sessionExpiryInterval(), std::forward<TFunc>(func));
            break;
        case FieldIdx_receiveMax:
            memFieldDispatch<FieldIdx_receiveMax>(accessField_receiveMax(), std::forward<TFunc>(func));
            break;
        case FieldIdx_maxQos:
            memFieldDispatch<FieldIdx_maxQos>(accessField_maxQos(), std::forward<TFunc>(func));
            break;
        case FieldIdx_retainAvailable:
            memFieldDispatch<FieldIdx_retainAvailable>(accessField_retainAvailable(), std::forward<TFunc>(func));
            break;
        case FieldIdx_maxPacketSize:
            memFieldDispatch<FieldIdx_maxPacketSize>(accessField_maxPacketSize(), std::forward<TFunc>(func));
            break;
        case FieldIdx_assignedClientId:
            memFieldDispatch<FieldIdx_assignedClientId>(accessField_assignedClientId(), std::forward<TFunc>(func));
            break;
        case FieldIdx_topicAliasMax:
            memFieldDispatch<FieldIdx_topicAliasMax>(accessField_topicAliasMax(), std::forward<TFunc>(func));
            break;
        case FieldIdx_reasonString:
            memFieldDispatch<FieldIdx_reasonString>(accessField_reasonString(), std::forward<TFunc>(func));
            break;
        case FieldIdx_userProperty:
            memFieldDispatch<FieldIdx_userProperty>(accessField_userProperty(), std::forward<TFunc>(func));
            break;
        case FieldIdx_wildcardSubAvail:
            memFieldDispatch<FieldIdx_wildcardSubAvail>(accessField_wildcardSubAvail(), std::forward<TFunc>(func));
            break;
        case FieldIdx_subIdAvail:
            memFieldDispatch<FieldIdx_subIdAvail>(accessField_subIdAvail(), std::forward<TFunc>(func));
            break;
        case FieldIdx_sharedSubAvail:
            memFieldDispatch<FieldIdx_sharedSubAvail>(accessField_sharedSubAvail(), std::forward<TFunc>(func));
            break;
        case FieldIdx_serverKeepAlive:
            memFieldDispatch<FieldIdx_serverKeepAlive>(accessField_serverKeepAlive(), std::forward<TFunc>(func));
            break;
        case FieldIdx_responseInfo:
            memFieldDispatch<FieldIdx_responseInfo>(accessField_responseInfo(), std::forward<TFunc>(func));
            break;
        case FieldIdx_serverReference:
            memFieldDispatch<FieldIdx_serverReference>(accessField_serverReference(), std::forward<TFunc>(func));
            break;
        case FieldIdx_authMethod:
            memFieldDispatch<FieldIdx_authMethod>(accessField_authMethod(), std::forward<TFunc>(func));
            break;
        case FieldIdx_authData:
            memFieldDispatch<FieldIdx_authData>(accessField_authData(), std::forward<TFunc>(func));
            break;
        default:
            static constexpr bool Invalid_field_execution = false;
            static_cast<void>(Invalid_field_execution);
            COMMS_ASSERT(Invalid_field_execution);
            break;
        }
    }

    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::ConnackPropertyCommon::name();
    }


private:
    template <std::size_t TIdx, typename TField, typename TFunc>
    static void memFieldDispatch(TField&& f, TFunc&& func)
    {
        #ifdef _MSC_VER
            func.operator()<TIdx>(std::forward<TField>(f)); // VS compiler
        #else // #ifdef _MSC_VER
            func.template operator()<TIdx>(std::forward<TField>(f)); // All other compilers
        #endif // #ifdef _MSC_VER
    }


};


} // namespace field

} // namespace mqtt5

