// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::HandshakeProperty field.

#pragma once

#include "mqtt5/field/ReasonStringCommon.h"
#include "mqtt5/field/UserPropertyCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::HandshakeProperty field.
struct HandshakePropertyMembersCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::HandshakePropertyMembers::ReasonString field.
    using ReasonStringMembersCommon = mqtt5::field::ReasonStringMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::field::HandshakePropertyMembers::ReasonString field.
    using ReasonStringCommon = mqtt5::field::ReasonStringCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::HandshakePropertyMembers::UserProperty field.
    using UserPropertyMembersCommon = mqtt5::field::UserPropertyMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::field::HandshakePropertyMembers::UserProperty field.
    using UserPropertyCommon = mqtt5::field::UserPropertyCommon;

};

/// @brief Common types and functions for
///     @ref mqtt5::field::HandshakeProperty field.
struct HandshakePropertyCommon
{
    /// @brief Name of the @ref mqtt5::field::HandshakeProperty field.
    static const char* name()
    {
        return "";
    }

};

} // namespace field

} // namespace mqtt5

