// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"Will Payload"</b> field.

#pragma once

#include "comms/field/Optional.h"
#include "comms/options.h"
#include "mqtt5/field/BinData.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/OptionalWillPayloadCommon.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the member fields of
///     @ref OptionalWillPayload field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct OptionalWillPayloadMembers
{
    /// @brief Definition of <b>"Will Payload"</b> field.
    class WillPayload : public
        mqtt5::field::BinData<
            TOpt
        >
    {
        using Base =
            mqtt5::field::BinData<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::field::OptionalWillPayloadMembersCommon::WillPayloadCommon::name();
        }


    };


};

/// @brief Definition of <b>"Will Payload"</b> field.
/// @details
///     Defined in section 3.1.3.4.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class OptionalWillPayload : public
    comms::field::Optional<
        typename OptionalWillPayloadMembers<TOpt>::WillPayload,
        TExtraOpts...,
        comms::option::def::MissingByDefault
    >
{
    using Base =
        comms::field::Optional<
            typename OptionalWillPayloadMembers<TOpt>::WillPayload,
            TExtraOpts...,
            comms::option::def::MissingByDefault
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::OptionalWillPayloadCommon::name();
    }


};


} // namespace field

} // namespace mqtt5

