// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::OptionalPassword field.

#pragma once

#include "mqtt5/field/BinDataCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::OptionalPassword field.
struct OptionalPasswordMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::OptionalPasswordMembers::Password field.
    struct PasswordCommon : public mqtt5::field::BinDataCommon
    {
        /// @brief Name of the @ref mqtt5::field::OptionalPasswordMembers::Password field.
        static const char* name()
        {
            return "Password";
        }

    };

};

/// @brief Common types and functions for
///     @ref mqtt5::field::OptionalPassword field.
struct OptionalPasswordCommon
{
    /// @brief Name of the @ref mqtt5::field::OptionalPassword field.
    static const char* name()
    {
        return "OptionalPassword";
    }

};

} // namespace field

} // namespace mqtt5

