// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"User name"</b> field.

#pragma once

#include "comms/field/Optional.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/OptionalUserNameCommon.h"
#include "mqtt5/field/Utf8String.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{

/// @brief Scope for all the member fields of
///     @ref OptionalUserName field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct OptionalUserNameMembers
{
    /// @brief Definition of <b>"User name"</b> field.
    class UserName : public
        mqtt5::field::Utf8String<
            TOpt
        >
    {
        using Base =
            mqtt5::field::Utf8String<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::field::OptionalUserNameMembersCommon::UserNameCommon::name();
        }
    };
};

/// @brief Definition of <b>"User name"</b> field.
/// @details
///     Defined in section 3.1.3.5.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class OptionalUserName : public
    comms::field::Optional<
        typename OptionalUserNameMembers<TOpt>::UserName,
        TExtraOpts...,
        comms::option::def::MissingByDefault
    >
{
    using Base =
        comms::field::Optional<
            typename OptionalUserNameMembers<TOpt>::UserName,
            TExtraOpts...,
            comms::option::def::MissingByDefault
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::OptionalUserNameCommon::name();
    }
};

} // namespace field

} // namespace mqtt5
