// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::OptionalWillPayload field.

#pragma once

#include "mqtt5/field/BinDataCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::OptionalWillPayload field.
struct OptionalWillPayloadMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::OptionalWillPayloadMembers::WillPayload field.
    struct WillPayloadCommon : public mqtt5::field::BinDataCommon
    {
        /// @brief Name of the @ref mqtt5::field::OptionalWillPayloadMembers::WillPayload field.
        static const char* name()
        {
            return "Will Payload";
        }

    };

};

/// @brief Common types and functions for
///     @ref mqtt5::field::OptionalWillPayload field.
struct OptionalWillPayloadCommon
{
    /// @brief Name of the @ref mqtt5::field::OptionalWillPayload field.
    static const char* name()
    {
        return "Will Payload";
    }

};

} // namespace field

} // namespace mqtt5

