// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"Packet ID"</b> field.

#pragma once

#include "comms/field/Optional.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/OptionalPacketIdentifierCommon.h"
#include "mqtt5/field/PacketIdentifier.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{

/// @brief Scope for all the member fields of
///     @ref OptionalPacketIdentifier field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct OptionalPacketIdentifierMembers
{
    /// @brief Definition of <b>"PacketIdentifier"</b> field.
    using PacketIdentifier =
        mqtt5::field::PacketIdentifier<
            TOpt
        >;
};

/// @brief Definition of <b>"Packet ID"</b> field.
/// @details
///     Defined in section 3.3.2.2.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class OptionalPacketIdentifier : public
    comms::field::Optional<
        typename OptionalPacketIdentifierMembers<TOpt>::PacketIdentifier,
        TExtraOpts...,
        comms::option::def::MissingByDefault
    >
{
    using Base =
        comms::field::Optional<
            typename OptionalPacketIdentifierMembers<TOpt>::PacketIdentifier,
            TExtraOpts...,
            comms::option::def::MissingByDefault
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::OptionalPacketIdentifierCommon::name();
    }
};

} // namespace field

} // namespace mqtt5
