// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"Will Topic"</b> field.

#pragma once

#include "comms/field/Optional.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/OptionalWillTopicCommon.h"
#include "mqtt5/field/TopicName.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the member fields of
///     @ref OptionalWillTopic field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct OptionalWillTopicMembers
{
    /// @brief Definition of <b>"Will Topic"</b> field.
    class WillTopic : public
        mqtt5::field::TopicName<
            TOpt
        >
    {
        using Base =
            mqtt5::field::TopicName<
                TOpt
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::field::OptionalWillTopicMembersCommon::WillTopicCommon::name();
        }


    };


};

/// @brief Definition of <b>"Will Topic"</b> field.
/// @details
///     Defined in section 3.1.3.3.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class OptionalWillTopic : public
    comms::field::Optional<
        typename OptionalWillTopicMembers<TOpt>::WillTopic,
        TExtraOpts...,
        comms::option::def::MissingByDefault
    >
{
    using Base =
        comms::field::Optional<
            typename OptionalWillTopicMembers<TOpt>::WillTopic,
            TExtraOpts...,
            comms::option::def::MissingByDefault
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::OptionalWillTopicCommon::name();
    }


};


} // namespace field

} // namespace mqtt5

