// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"Puback Properties"</b> field.

#pragma once

#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/PubackProperties.h"
#include "mqtt5/field/PubrelPropertiesCommon.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Definition of <b>"Puback Properties"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
using PubrelProperties =
    mqtt5::field::PubackProperties<
        TOpt,
        TExtraOpts...
    >;


} // namespace field

} // namespace mqtt5

