// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::ReasonStr field.

#pragma once

#include <cstdint>
#include "mqtt5/field/StringCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::ReasonStr field.
struct ReasonStrMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ReasonStrMembers::Id field.
    struct IdCommon
    {
        /// @brief Re-definition of the value type used by
        ///     mqtt5::field::ReasonStrMembers::Id field.
        using ValueType = std::uint32_t;
        
        /// @brief Name of the @ref mqtt5::field::ReasonStrMembers::Id field.
        static const char* name()
        {
            return "Id";
        }
        
        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
        
        
    };
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::ReasonStrMembers::Value field.
    struct ValueCommon : public mqtt5::field::StringCommon
    {
        /// @brief Name of the @ref mqtt5::field::ReasonStrMembers::Value field.
        static const char* name()
        {
            return "Value";
        }
        
    };
    
};

/// @brief Common types and functions for
///     @ref mqtt5::field::ReasonStr field.
struct ReasonStrCommon
{
    /// @brief Name of the @ref mqtt5::field::ReasonStr field.
    static const char* name()
    {
        return "Reason String";
    }
    
};

} // namespace field

} // namespace mqtt5

