// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"SubscribePayload"</b> field.

#pragma once

#include "comms/field/ArrayList.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/SubscribePayloadCommon.h"
#include "mqtt5/field/SubscribePayloadElement.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the member fields of
///     @ref SubscribePayload field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct SubscribePayloadMembers
{
    /// @brief Definition of <b>""</b> field.
    using Element =
        mqtt5::field::SubscribePayloadElement<
            TOpt
        >;


};

/// @brief Definition of <b>"SubscribePayload"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class SubscribePayload : public
    comms::field::ArrayList<
        mqtt5::field::FieldBase<>,
        typename SubscribePayloadMembers<TOpt>::Element,
        TExtraOpts...,
        typename TOpt::field::SubscribePayload
    >
{
    using Base =
        comms::field::ArrayList<
            mqtt5::field::FieldBase<>,
            typename SubscribePayloadMembers<TOpt>::Element,
            TExtraOpts...,
            typename TOpt::field::SubscribePayload
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::SubscribePayloadCommon::name();
    }


};


} // namespace field

} // namespace mqtt5

