// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::SubscribeProperties field.

#pragma once

#include <cstdint>
#include "mqtt5/field/SubscribePropertyCommon.h"

namespace mqtt5
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::SubscribeProperties field.
struct SubscribePropertiesMembersCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::SubscribePropertiesMembers::Properties field.
    using PropertiesMembersCommon = mqtt5::field::SubscribePropertyMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::field::SubscribePropertiesMembers::Properties field.
    using PropertiesCommon = mqtt5::field::SubscribePropertyCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::field::SubscribePropertiesMembers::Length field.
    struct LengthCommon
    {
        /// @brief Re-definition of the value type used by
        ///     mqtt5::field::SubscribePropertiesMembers::Length field.
        using ValueType = std::uint32_t;

        /// @brief Name of the @ref mqtt5::field::SubscribePropertiesMembers::Length field.
        static const char* name()
        {
            return "Length";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };
};

/// @brief Common types and functions for
///     @ref mqtt5::field::SubscribeProperties field.
struct SubscribePropertiesCommon
{
    /// @brief Name of the @ref mqtt5::field::SubscribeProperties field.
    static const char* name()
    {
        return "Subscribe properties";
    }
};

} // namespace field

} // namespace mqtt5
