// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"Subscribe properties"</b> field.

#pragma once

#include <cstdint>
#include "comms/field/ArrayList.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/SubscribePropertiesCommon.h"
#include "mqtt5/field/SubscribeProperty.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{

/// @brief Scope for all the member fields of
///     @ref SubscribeProperties field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct SubscribePropertiesMembers
{
    /// @brief Definition of <b>"Property"</b> field.
    using Properties =
        mqtt5::field::SubscribeProperty<
            TOpt
        >;

    /// @brief Definition of <b>"Length"</b> field.
    /// @details
    ///     Defined in section 2.2.2.1.
    class Length : public
        comms::field::IntValue<
            mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
            std::uint32_t,
            comms::option::def::VarLength<1U, 4U>,
            comms::option::def::UnitsBytes
        >
    {
        using Base =
            comms::field::IntValue<
                mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
                std::uint32_t,
                comms::option::def::VarLength<1U, 4U>,
                comms::option::def::UnitsBytes
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return mqtt5::field::SubscribePropertiesMembersCommon::LengthCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::field::SubscribePropertiesMembersCommon::LengthCommon::name();
        }
    };
};

/// @brief Definition of <b>"Subscribe properties"</b> field.
/// @details
///     Defined in section 3.8.2.1.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class SubscribeProperties : public
    comms::field::ArrayList<
        mqtt5::field::FieldBase<>,
        typename SubscribePropertiesMembers<TOpt>::Properties,
        TExtraOpts...,
        typename TOpt::field::SubscribeProperties,
        comms::option::def::SequenceSerLengthFieldPrefix<typename SubscribePropertiesMembers<TOpt>::Length>
    >
{
    using Base =
        comms::field::ArrayList<
            mqtt5::field::FieldBase<>,
            typename SubscribePropertiesMembers<TOpt>::Properties,
            TExtraOpts...,
            typename TOpt::field::SubscribeProperties,
            comms::option::def::SequenceSerLengthFieldPrefix<typename SubscribePropertiesMembers<TOpt>::Length>
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::SubscribePropertiesCommon::name();
    }
};

} // namespace field

} // namespace mqtt5
