// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"TopicName"</b> field.

#pragma once

#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/String.h"
#include "mqtt5/field/TopicNameCommon.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Definition of <b>"TopicName"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class TopicName : public
    mqtt5::field::String<
        TOpt,
        TExtraOpts...
    >
{
    using Base =
        mqtt5::field::String<
            TOpt,
            TExtraOpts...
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::TopicNameCommon::name();
    }
    

};


} // namespace field

} // namespace mqtt5

