// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::TopicAlias field.

#pragma once

#include <cstdint>

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::TopicAlias field.
struct TopicAliasMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::TopicAliasMembers::Id field.
    struct IdCommon
    {
        /// @brief Re-definition of the value type used by
        ///     mqtt5::field::TopicAliasMembers::Id field.
        using ValueType = std::uint32_t;
        
        /// @brief Name of the @ref mqtt5::field::TopicAliasMembers::Id field.
        static const char* name()
        {
            return "Id";
        }
        
        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
        
        
    };
    
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::TopicAliasMembers::Value field.
    struct ValueCommon
    {
        /// @brief Re-definition of the value type used by
        ///     mqtt5::field::TopicAliasMembers::Value field.
        using ValueType = std::uint16_t;
        
        /// @brief Name of the @ref mqtt5::field::TopicAliasMembers::Value field.
        static const char* name()
        {
            return "Value";
        }
        
        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
        
        
    };
    
};

/// @brief Common types and functions for
///     @ref mqtt5::field::TopicAlias field.
struct TopicAliasCommon
{
    /// @brief Name of the @ref mqtt5::field::TopicAlias field.
    static const char* name()
    {
        return "Topic Alias";
    }
    
};

} // namespace field

} // namespace mqtt5

