// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::UnsubackPropertyList field.

#pragma once

#include "mqtt5/field/HandshakePropertyListCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Common definitions of the member fields of
///     @ref mqtt5::field::UnsubackPropertyList field.
using UnsubackPropertyListMembersCommon = mqtt5::field::HandshakePropertyListMembersCommon;

/// @brief Common types and functions for
///     @ref mqtt5::field::UnsubackPropertyList field.
using UnsubackPropertyListCommon = mqtt5::field::HandshakePropertyListCommon;

} // namespace field

} // namespace mqtt5

