// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::UnsubscribeProperty field.

#pragma once

#include "mqtt5/field/UserPropertyCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::UnsubscribeProperty field.
struct UnsubscribePropertyMembersCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref mqtt5::field::UnsubscribePropertyMembers::UserProperty field.
    using UserPropertyMembersCommon = mqtt5::field::UserPropertyMembersCommon;

    /// @brief Common types and functions for
    ///     @ref mqtt5::field::UnsubscribePropertyMembers::UserProperty field.
    using UserPropertyCommon = mqtt5::field::UserPropertyCommon;

};

/// @brief Common types and functions for
///     @ref mqtt5::field::UnsubscribeProperty field.
struct UnsubscribePropertyCommon
{
    /// @brief Name of the @ref mqtt5::field::UnsubscribeProperty field.
    static const char* name()
    {
        return "";
    }

};

} // namespace field

} // namespace mqtt5

