// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"Unsubscribe Properties"</b> field.

#pragma once

#include <cstdint>
#include "comms/field/ArrayList.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/UnsubscribePropertiesCommon.h"
#include "mqtt5/field/UnsubscribeProperty.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the member fields of
///     @ref UnsubscribeProperties field.
/// @tparam TOpt Protocol options.
template <typename TOpt = mqtt5::options::DefaultOptions>
struct UnsubscribePropertiesMembers
{
    /// @brief Definition of <b>""</b> field.
    using Properties =
        mqtt5::field::UnsubscribeProperty<
            TOpt
        >;


    /// @brief Definition of <b>"Length"</b> field.
    /// @details
    ///     Defined in section 2.2.2.1.
    class Length : public
        comms::field::IntValue<
            mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
            std::uint32_t,
            comms::option::def::VarLength<1U, 4U>,
            comms::option::def::UnitsBytes
        >
    {
        using Base =
            comms::field::IntValue<
                mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
                std::uint32_t,
                comms::option::def::VarLength<1U, 4U>,
                comms::option::def::UnitsBytes
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return mqtt5::field::UnsubscribePropertiesMembersCommon::LengthCommon::hasSpecials();
        }


        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::field::UnsubscribePropertiesMembersCommon::LengthCommon::name();
        }


    };


};

/// @brief Definition of <b>"Unsubscribe Properties"</b> field.
/// @details
///     Defined in section 3.10.2.1.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class UnsubscribeProperties : public
    comms::field::ArrayList<
        mqtt5::field::FieldBase<>,
        typename UnsubscribePropertiesMembers<TOpt>::Properties,
        TExtraOpts...,
        typename TOpt::field::UnsubscribeProperties,
        comms::option::def::SequenceSerLengthFieldPrefix<typename UnsubscribePropertiesMembers<TOpt>::Length>
    >
{
    using Base =
        comms::field::ArrayList<
            mqtt5::field::FieldBase<>,
            typename UnsubscribePropertiesMembers<TOpt>::Properties,
            TExtraOpts...,
            typename TOpt::field::UnsubscribeProperties,
            comms::option::def::SequenceSerLengthFieldPrefix<typename UnsubscribePropertiesMembers<TOpt>::Length>
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::UnsubscribePropertiesCommon::name();
    }


};


} // namespace field

} // namespace mqtt5

