// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::UserProperty field.

#pragma once

#include <cstdint>
#include "mqtt5/field/StringCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Scope for all the common definitions of the member fields of
///     @ref mqtt5::field::UserProperty field.
struct UserPropertyMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt5::field::UserPropertyMembers::Id field.
    struct IdCommon
    {
        /// @brief Re-definition of the value type used by
        ///     mqtt5::field::UserPropertyMembers::Id field.
        using ValueType = std::uint32_t;

        /// @brief Name of the @ref mqtt5::field::UserPropertyMembers::Id field.
        static const char* name()
        {
            return "Id";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }


    };

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref mqtt5::field::UserPropertyMembers::Value field.
    struct ValueMembersCommon
    {
        /// @brief Common types and functions for
        ///     @ref mqtt5::field::UserPropertyMembers::ValueMembers::First field.
        struct FirstCommon : public mqtt5::field::StringCommon
        {
            /// @brief Name of the @ref mqtt5::field::UserPropertyMembers::ValueMembers::First field.
            static const char* name()
            {
                return "First";
            }

        };

        /// @brief Common types and functions for
        ///     @ref mqtt5::field::UserPropertyMembers::ValueMembers::Second field.
        struct SecondCommon : public mqtt5::field::StringCommon
        {
            /// @brief Name of the @ref mqtt5::field::UserPropertyMembers::ValueMembers::Second field.
            static const char* name()
            {
                return "Second";
            }

        };

    };

    /// @brief Common types and functions for
    ///     @ref mqtt5::field::UserPropertyMembers::Value field.
    struct ValueCommon
    {
        /// @brief Name of the @ref mqtt5::field::UserPropertyMembers::Value field.
        static const char* name()
        {
            return "Value";
        }

    };

};

/// @brief Common types and functions for
///     @ref mqtt5::field::UserProperty field.
struct UserPropertyCommon
{
    /// @brief Name of the @ref mqtt5::field::UserProperty field.
    static const char* name()
    {
        return "User Property";
    }

};

} // namespace field

} // namespace mqtt5

