// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"Utf8String"</b> field.

#pragma once

#include "comms/field/String.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/Utf8StringCommon.h"
#include "mqtt5/field/Utf8StringLength.h"
#include "mqtt5/options/DefaultOptions.h"

#include "external/utf8_validation.h"

namespace mqtt5
{

namespace field
{

/// @brief Definition of <b>"Utf8String"</b> field.
/// @details
///     Defined in section 1.5.4.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class Utf8String : public
    comms::field::String<
        mqtt5::field::FieldBase<>,
        TExtraOpts...,
        typename TOpt::field::Utf8String,
        comms::option::def::SequenceSerLengthFieldPrefix<mqtt5::field::Utf8StringLength<TOpt> >
    >
{
    using Base =
        comms::field::String<
            mqtt5::field::FieldBase<>,
            TExtraOpts...,
            typename TOpt::field::Utf8String,
            comms::option::def::SequenceSerLengthFieldPrefix<mqtt5::field::Utf8StringLength<TOpt> >
        >;
public:
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::Utf8StringCommon::name();
    }

    /// @brief Custom validity check
    bool valid() const
    {
        return ::utf8::valid_mqtt_string(
            reinterpret_cast< unsigned char const * >( Utf8String().value().c_str() ));
    }
};

} // namespace field

} // namespace mqtt5
