// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::Utf8String field.

#pragma once

namespace mqtt5
{

namespace field
{


/// @brief Common types and functions for
///     @ref mqtt5::field::Utf8String field.
struct Utf8StringCommon
{
    /// @brief Name of the @ref mqtt5::field::Utf8String field.
    static const char* name()
    {
        return "Utf8String";
    }

};

} // namespace field

} // namespace mqtt5

